sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm cache clean
  - npm install -g reflect-metadata
  - npm install -g angular-cli
  - npm install -g karma
  - bin/firebase-credentials.sh $FIREBASE_APP_NAME $FIREBASE_API_KEY $FIREBASE_SENDER_ID
  - npm install
  - ng build

script: karma start karma.conf.js --single-run
